languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Cholf's Blog"
#copyright = "&copy; 2024 Congo contributors"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["posts"]
  description = "Record what Cholf saw, heard, thought, and life journey. All mortals will die, and most people will not leave any traces. But I, an ordinary person, hope to leave some traces through my writing."

[params.author]
  name = "Cholf"
  image = "img/author.jpg"
  headline = "Make Fun Games!"
  bio = "Just because you can, doesn't mean you should."
  links = [
    { twitter = "https://x.com/cholf5" },
    { github = "https://github.com/cholf5" },
  ]
